export const constants = {
  ACCESS_TOKEN_KEY: "ACCESS_TOKEN_KEY",
  BASE_URL: "BASE_URL",
  DATE_FORMAT: "MMMM D, YYYY",
  ENTER_KEY_CODE: 13,
  MINIMUM_LOG_LEVEL: "MINIMUM_LOG_LEVEL",
  STORAGE_KEY: "[Macaria] STORAGE_KEY",
  TENANT_KEY: "TENANT_KEY",
  CULTURE_KEY: "CULTURE_KEY",
  SIGNALR_CONNECTION_ID_KEY: "SIGNALR_CONNECTION_ID_KEY"
};
